import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import logo from './assets/logo.svg';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <header className="border-b border-gray-200">
        <div className="container mx-auto px-4 py-4 flex justify-between items-center">
            <div className="flex items-center">
                <a href="./index.html">
                     <Image 
                    src={logo}
                    alt="My Photo" 
                    width={150}
                    height={100} 
                  />
                </a>
            </div>
            
            <nav className="hidden md:flex items-center space-x-6">

                <a href="#" className="bg-black text-white px-4 py-2 rounded-full hover:bg-gray-800 transition-colors">Get started</a>
            </nav>
            
            <button className="md:hidden">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                </svg>
            </button>
        </div>
    </header>
        {children}
      </body>
    </html>
  );
}
